services:
  frontend:
    build:
      context: ../
      dockerfile: apps/frontend/Dockerfile
    container_name: fit-frontend
    ports:
      - '3001:80'
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ../
      dockerfile: apps/backend/Dockerfile
    container_name: fit-backend
    ports:
      - '3000:3000'
    env_file:
      - ../apps/backend/.env
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    container_name: fit-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fittracker
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  db_data:

networks:
  default:
    name: fit-network
