name: CI Pipeline (Brute-Force)

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        # fetch-depth: 0 більше не потрібен

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Lint and Test for ALL projects
        run: |
          pnpm exec nx run-many --all --target=lint --parallel
          pnpm exec nx run-many --all --target=test --parallel
